### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by v-fox** [maazl/easytag#2]
Tried [building it on openSUSE](https://build.opensuse.org/package/show/home:X0F:branches:multimedia/easytag) and have got some issues:

First OBS yelled:
```configure
[   24s] ./configure: line 19199: syntax error near unexpected token `11,noext,mandatory'
[   24s] ./configure: line 19199: `AX_CXX_COMPILE_STDCXX(11,noext,mandatory)'
```
Which seems to be introduced in 4fe9422258cdefab550facde2e807267a209adca, so I did:
```patch
diff --git a/configure.ac b/configure.ac
index 12629cb..f62fc0a 100644
--- a/configure.ac
+++ b/configure.ac
@@ -47,7 +47,7 @@ AC_PROG_CC
 AC_PROG_CC_C99
 AC_PROG_CXX
 AC_PROG_CXXCPP
-AX_CXX_COMPILE_STDCXX([11],[noext],[mandatory])
+AX_CXX_COMPILE_STDCXX
 AC_PROG_SED
 PKG_PROG_PKG_CONFIG([0.24])
 
```

Then [taglib-2.0.patch] needed rebasing:
<details><summary>easytag-taglib-2.0.patch</summary>

```patch
diff --git a/src/tags/gio_wrapper.cc b/src/tags/gio_wrapper.cc
index 8716331..8772d52 100644
--- a/src/tags/gio_wrapper.cc
+++ b/src/tags/gio_wrapper.cc
@@ -47,11 +47,11 @@ GIO_InputStream::name () const
 }
 
 TagLib::ByteVector
-GIO_InputStream::readBlock (TagLib::ulong len)
+GIO_InputStream::readBlock (ulong len)
 {
     if (error)
     {
-        return TagLib::ByteVector::null;
+        return TagLib::ByteVector();
     }
 
     TagLib::ByteVector rv (len, 0);
@@ -70,14 +70,14 @@ GIO_InputStream::writeBlock (TagLib::ByteVector const &data)
 
 void
 GIO_InputStream::insert (TagLib::ByteVector const &data,
-                         TagLib::ulong start,
-                         TagLib::ulong replace)
+                         TagLib::offset_t start,
+                         size_t replace)
 {
     g_warning ("%s", "Trying to write to read-only file!");
 }
 
 void
-GIO_InputStream::removeBlock (TagLib::ulong start, TagLib::ulong len)
+GIO_InputStream::removeBlock (TagLib::offset_t start, size_t len)
 {
     g_warning ("%s", "Trying to write to read-only file!");
 }
@@ -200,11 +200,11 @@ GIO_IOStream::name () const
 }
 
 TagLib::ByteVector
-GIO_IOStream::readBlock (TagLib::ulong len)
+GIO_IOStream::readBlock (ulong len)
 {
     if (error)
     {
-        return TagLib::ByteVector::null;
+        return TagLib::ByteVector();
     }
 
     gsize bytes = 0;
@@ -239,8 +239,8 @@ GIO_IOStream::writeBlock (TagLib::ByteVector const &data)
 
 void
 GIO_IOStream::insert (TagLib::ByteVector const &data,
-                      TagLib::ulong start,
-                      TagLib::ulong replace)
+                      TagLib::offset_t start,
+                      size_t replace)
 {
     if (error)
     {
@@ -351,9 +351,9 @@ GIO_IOStream::insert (TagLib::ByteVector const &data,
 }
 
 void
-GIO_IOStream::removeBlock (TagLib::ulong start, TagLib::ulong len)
+GIO_IOStream::removeBlock (TagLib::offset_t start, size_t len)
 {
-    if (start + len >= (TagLib::ulong)length ())
+    if (start + len >= (ulong)length ())
     {
         truncate (start);
         return;
diff --git a/src/tags/gio_wrapper.h b/src/tags/gio_wrapper.h
index e49e54d..2f80d3a 100644
--- a/src/tags/gio_wrapper.h
+++ b/src/tags/gio_wrapper.h
@@ -33,10 +33,10 @@ public:
     GIO_InputStream (GFile *file_);
     virtual ~GIO_InputStream ();
     virtual TagLib::FileName name () const;
-    virtual TagLib::ByteVector readBlock (TagLib::ulong length);
+    virtual TagLib::ByteVector readBlock (ulong length);
     virtual void writeBlock (TagLib::ByteVector const &data);
-    virtual void insert (TagLib::ByteVector const &data, TagLib::ulong start = 0, TagLib::ulong replace = 0);
-    virtual void removeBlock (TagLib::ulong start = 0, TagLib::ulong length = 0);
+    virtual void insert (TagLib::ByteVector const &data, TagLib::offset_t start = 0, size_t replace = 0);
+    virtual void removeBlock (TagLib::offset_t start = 0, size_t length = 0);
     virtual bool readOnly () const;
     virtual bool isOpen () const;
     virtual void seek (long int offset, TagLib::IOStream::Position p = TagLib::IOStream::Beginning);
@@ -61,10 +61,10 @@ public:
     GIO_IOStream (GFile *file_);
     virtual ~GIO_IOStream ();
     virtual TagLib::FileName name () const;
-    virtual TagLib::ByteVector readBlock (TagLib::ulong length);
+    virtual TagLib::ByteVector readBlock (ulong length);
     virtual void writeBlock (TagLib::ByteVector const &data);
-    virtual void insert (TagLib::ByteVector const &data, TagLib::ulong start = 0, TagLib::ulong replace = 0);
-    virtual void removeBlock (TagLib::ulong start = 0, TagLib::ulong len = 0);
+    virtual void insert (TagLib::ByteVector const &data, TagLib::offset_t start = 0, size_t replace = 0);
+    virtual void removeBlock (TagLib::offset_t start = 0, size_t length = 0);
     virtual bool readOnly () const;
     virtual bool isOpen () const;
     virtual void seek (long int offset, TagLib::IOStream::Position p = TagLib::IOStream::Beginning);
diff --git a/src/tags/mp4_tag.cc b/src/tags/mp4_tag.cc
index 7e1dd5e..4bb7b79 100644
--- a/src/tags/mp4_tag.cc
+++ b/src/tags/mp4_tag.cc
@@ -167,27 +167,15 @@ mp4tag_read_file_tag (GFile *file,
     if (extra_tag.contains ("ENCODEDBY"))
         et_file_tag_set_encoded_by(FileTag, extra_tag["ENCODEDBY"].front().toCString(true));
 
-    const TagLib::MP4::ItemListMap &extra_items = tag->itemListMap ();
+    const TagLib::MP4::ItemMap &extra_items = tag->itemMap ();
 
     /* Album Artist */
-#if (TAGLIB_MAJOR_VERSION == 1) && (TAGLIB_MINOR_VERSION < 10)
-    /* No "ALBUMARTIST" support in TagLib until 1.10; use atom directly. */
-    if (extra_items.contains ("aART"))
-        et_file_tag_set_album_artist(FileTag, extra_items["aART"].toStringList().front().toCString(true));
-#else
     if (extra_tag.contains ("ALBUMARTIST"))
         et_file_tag_set_album_artist(FileTag, extra_tag["ALBUMARTIST"].front().toCString(true));
-#endif
 
     /* Description */
-#if (TAGLIB_MAJOR_VERSION == 1) && (TAGLIB_MINOR_VERSION < 12)
-    /* No "PODCASTDESC" support in TagLib until 1.12; use atom directly. */
-    if (extra_items.contains ("desc"))
-        et_file_tag_set_description(FileTag, extra_items["desc"].toStringList().front().toCString(true));
-#else
     if (extra_tag.contains ("PODCASTDESC"))
         et_file_tag_set_description(FileTag, extra_tag["PODCASTDESC"].front().toCString(true));
-#endif
 
     // TOD support ReplayGain, requires TagLib 2.0
 
@@ -316,38 +304,18 @@ mp4tag_write_file_tag (const ET_File *ETFile,
 
     add_field(FileTag->encoded_by, "ENCODEDBY");
 
-    TagLib::MP4::ItemListMap &extra_items = tag->itemListMap ();
-
     /* Album artist. */
     if (!et_str_empty (FileTag->album_artist))
     {
         TagLib::String string (FileTag->album_artist, TagLib::String::UTF8);
-#if (TAGLIB_MAJOR_VERSION == 1) && (TAGLIB_MINOR_VERSION < 10)
-        /* No "ALBUMARTIST" support in TagLib until 1.10; use atom directly. */
-        extra_items.insert ("aART", TagLib::MP4::Item (string));
-    }
-    else
-    {
-        extra_items.erase ("aART");
-#else
         fields.insert ("ALBUMARTIST", string);
-#endif
     }
 
     /* Description. */
     if (!et_str_empty (FileTag->description))
     {
         TagLib::String string (FileTag->description, TagLib::String::UTF8);
-#if (TAGLIB_MAJOR_VERSION == 1) && (TAGLIB_MINOR_VERSION < 12)
-        /* No "PODCASTDESC" support in TagLib until 1.12; use atom directly. */
-        extra_items.insert ("desc", TagLib::MP4::Item (string));
-    }
-    else
-    {
-        extra_items.erase ("desc");
-#else
         fields.insert ("PODCASTDESC", string);
-#endif
     }
 
     // TOD support ReplayGain, requires TagLib 2.0
@@ -386,12 +354,12 @@ mp4tag_write_file_tag (const ET_File *ETFile,
         TagLib::MP4::CoverArt art (f, TagLib::ByteVector((char *)data,
                                                          data_size));
 
-        extra_items.insert ("covr",
+        tag->setItem("covr",
                             TagLib::MP4::Item (TagLib::MP4::CoverArtList ().append (art)));
     }
     else
     {
-        extra_items.erase ("covr");
+        tag->removeItem("covr");
     }
 
     tag->setProperties (fields);
```

</details>

Unfortunately, not only it seems to be still affected by my original issue of ["Process Fields" function in scanner crashing](https://gitlab.gnome.org/GNOME/easytag/-/issues/104) but there is also new issue of screwy palette under dark theme:
![easytag](https://github.com/maazl/easytag/assets/362763/6d58c558-05e5-4797-a8a0-6283de7d913b)

**Comment by maazl** [comment]
These are different issues.

1. AX_CXX_COMPILE_STDCXX
Removing the C++ standard version breaks other platforms. E.g. Debian/gcc refuses to use newer C++ standards without the compiler option --std=c++11. Are old versions of AX_CXX_COMPILE_STDCXX around that do not support newer C++ standards? AFAIK the macro with C++ version 11 is supported since 2015. Or does the macro on some platforms require a space after each comma? No idea.

2. Theming
This is not supported so far.
Either colors should be applied in some differential manner or the colors need to be configurable. I wonder a bit why this works in the original version.

3. Taglib 2.0
I plan to move to Taglib 2.0 because this is required to access ReplayGain tags in M4A files. But first I need to get Taglib 2.0 working on my platform.

4. Process fields
Fixed.

**Comment by v-fox** [comment]
> These are different issues.

Well, that's why I called them "issues" in the title. Separating was too exhausting after fiddling with one after another even though I only wanted to test out the last one.



> 1. AX_CXX_COMPILE_STDCXX
>        Removing the C++ standard version breaks other platforms. E.g. Debian/gcc refuses to use newer C++ standards without the compiler option --std=c++11. Are old versions of AX_CXX_COMPILE_STDCXX around that do not support newer C++ standards? AFAIK the macro with C++ version 11 is supported since 2015. Or does the macro on some platforms require a space after each comma? No idea.

Have no idea but it made VM builder of openSUSE's Open Build Service happy. And it uses pretty new version of gcc/glibc. See https://build.opensuse.org/package/show/openSUSE:Factory/gcc13 and https://build.opensuse.org/package/show/openSUSE:Factory/glibc

> 2\. Theming
>         This is not supported so far.
>         Either colors should be applied in some differential manner or the colors need to be configurable. I wonder a bit why this works in the original version.

I also run it under KDE/Plasma 6 build against Qt6 (but still with X11 instead of coerced Wayland), this may have some effect on GTK themes. I remember at some point original ET also having same issue but then it went away. Maybe after openSUSE transitioned from latest release to latest snapshot. Or maybe due to some changes that KDE does in forcing GTK apps to follow its themes.
Weirdly, it's only an issue with that one alternating row background colour. Tried getting rid from ~/.config/gtk-3.0/colors.css generated by KDE but it did not affect ET.

I assumed that your fork is synced with original's latest snapshot, so it would look the same.

It also seems to be sometimes segfaulting on exit with:
```coredump
                Stack trace of thread 25026:
                #0  0x00007f570b338c29 gtk_widget_destroy (libgtk-3.so.0 + 0x338c29)
                #1  0x000055f103d005f5 n/a (easytag + 0x2b5f5)
                #2  0x00007f570ad5a668 g_closure_invoke (libgobject-2.0.so.0 + 0x17668)
                #3  0x00007f570ad6f50d n/a (libgobject-2.0.so.0 + 0x2c50d)
                #4  0x00007f570ad70911 n/a (libgobject-2.0.so.0 + 0x2d911)
                #5  0x00007f570ad765c2 g_signal_emit_valist (libgobject-2.0.so.0 + 0x335c2)
                #6  0x00007f570ad7666f g_signal_emit (libgobject-2.0.so.0 + 0x3366f)
                #7  0x00007f570b346728 n/a (libgtk-3.so.0 + 0x346728)
```

> 3\. Taglib 2.0
>         I plan to move to Taglib 2.0 because this is required to access ReplayGain tags in M4A files. But first I need to get Taglib 2.0 working on my platform.

openSUSE has transitioned to taglib-2, so there is no choice for me. Luckily, they already had the patch, so I only had to rebase it manually.

> 4\. Process fields
>         Fixed.

Nice. Thanks! That's exactly what I needed to fix up some weirdly capitalized album.

**Comment by maazl** [comment]
- I added spaces to AX_CXX_COMPILE_STDCXX parameters. Can you check whether this fixes the build issue for OpenSuse?
- TagLib 2.0 is now supported (and recommended for full MP4 support including ReplayGain).

**Comment by v-fox** [comment]
> * I added spaces to AX_CXX_COMPILE_STDCXX parameters. Can you check whether this fixes the build issue for OpenSuse?

Unfortunately, this had no difference. It says:
```
[   24s] ./configure: line 19199: syntax error near unexpected token `11,'
[   24s] ./configure: line 19199: `AX_CXX_COMPILE_STDCXX(11, noext, mandatory)'
```
autoconf is version 2.72, by the way, and automake is 1.16.5.

> * TagLib 2.0 is now supported (and recommended for full MP4 support including ReplayGain).

Seems to be compiling and working fine without the patch now.

Now if only that annoying colour issue would be gone, it would be perfect.

**Comment by maazl** [comment]
I am using autoconf 2.69, but I think the version is not important. It depends on the version of the particular m4 script, probably /usr/share/aclocal/ac_cxx_compile_stdcxx.m4. Or there is an old version in another path. But I definitely cannot remove the options, since the defaults differ.

> Now if only that annoying colour issue would be gone, it would be perfect.

Well, this is my first work with GTK. I have no idea how to query theme colors. Any hint is appreciated. 
I also use a dark theme, but with my Gnome version this seems not affect EasyTag (and many other applications).

The only quick fix I see is that you can change the hard coded color in file_renderer.cc. But I really wonder why this should work with the original version of EasyTag since it has the same color hard coded in browser.c too. The only difference is that in the original version the zebra color is only applied to different folder names while in my branch it depends on the first sort criterion.

**Comment by v-fox** [comment]
> I am using autoconf 2.69, but I think the version is not important. It depends on the version of the particular m4 script, probably /usr/share/aclocal/ac_cxx_compile_stdcxx.m4. Or there is an old version in another path. But I definitely cannot remove the options, since the defaults differ.

I think I figured it out. I had no such file with autoconf installed, so I've decided to look what relevant packages are available. There was one called `autoconf-archive` and after adding it configure seems to stop failing.

But then it failed compilation with:
```
[   35s] g++ -std=c++11 -DHAVE_CONFIG_H   -I. -I./src -I./src/tags -I. -I./src -DLOCALEDIR=\"/usr/share/locale\" -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_56 -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_14 -DGDK_VERSION_MAX_ALLOWED=GDK_VERSION_3_14 -DSOUP_VERSION_MIN_REQUIRED=SOUP_VERSION_2_42 -DSOUP_VERSION_MAX_ALLOWED=SOUP_VERSION_2_42  -fno-strict-aliasing -I/usr/include/libsoup-2.4 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -pthread -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/opus -I/usr/include/taglib -I/usr/include/libxml2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/libxkbcommon -I/usr/include/fribidi -I/usr/include/gio-unix-2.0 -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -O2 -c -o src/easytag-tag_area.o `test -f 'src/tag_area.cc' || echo './'`src/tag_area.cc
[   35s] src/tag_area.cc: In lambda function:
[   35s] src/tag_area.cc:2581:34: error: ‘numeric_limits’ was not declared in this scope
[   35s]  2581 |                 {       target = numeric_limits<float>::quiet_NaN();
[   35s]       |                                  ^~~~~~~~~~~~~~
[   35s] src/tag_area.cc:2581:49: error: expected primary-expression before ‘float’
[   35s]  2581 |                 {       target = numeric_limits<float>::quiet_NaN();
[   35s]       |                                                 ^~~~~
````

I've noticed that configuration said `ReplayGain support: no` which seem to be caused by me missing addition of  ffmpeg dependencies.

Adding them changes error to:
```
[   36s] src/replaygain.cc: In member function ‘std::string ReplayGainAnalyzer::AnalyzeFile(const char*)’:
[   36s] src/replaygain.cc:417:48: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
[   36s]   417 |         AVCodec* decoder = avcodec_find_decoder(stream->codecpar->codec_id);
[   36s]       |                            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   36s]       |                                                |
[   36s]       |                                                const AVCodec*
```

Seems like, with and without ffmpeg, compilation is broken. openSUSE uses latest ffmpeg release of 6.1.1.
Adding `-fpermissive` flag (which should not be done in distros) has returned error to `‘numeric_limits’ was not declared in this scope`.

> The only quick fix I see is that you can change the hard coded color in file_renderer.cc. But I really wonder why this should work with the original version of EasyTag since it has the same color hard coded in browser.c too. The only difference is that in the original version the zebra color is only applied to different folder names while in my branch it depends on the first sort criterion.

I've reinstalled the original to check and it seems to not use alternating background at all in all sorting modes.
In the fork selecting "View -> Sort list by property -> file path / file type / bit rate / sample rate" works around it by not having alternating lines too.

**Comment by maazl** [comment]
Without ffmpeg: This was simply a missing include. Fixed.

With ffmpeg: probably the constness of the returned pointer has changed. Changed tho code to const AVCodec*. This seems not to harm the older versions of the API.

-O2: optimizations did not work without this hack. I updated AX_CHECK_ENABLE_DEBUG and patched it not to add -O2 if user flags are set.

**Comment by v-fox** [comment]
Nice.

But now it failed with:
```
[   37s] src/tags/ogg_tag.cc: In lambda function:
[   37s] src/tags/ogg_tag.cc:250:32: error: ‘numeric_limits’ was not declared in this scope
[   37s]   250 |                         return numeric_limits<float>::quiet_NaN();
[   37s]       |                                ^~~~~~~~~~~~~~
[   37s] src/tags/ogg_tag.cc:250:47: error: expected primary-expression before ‘float’
[   37s]   250 |                         return numeric_limits<float>::quiet_NaN();
[   37s]       |                                               ^~~~~
[   37s] src/tags/ogg_tag.cc:250:47: error: expected ‘;’ before ‘float’
[   37s]   250 |                         return numeric_limits<float>::quiet_NaN();
[   37s]       |                                               ^~~~~
[   37s]       |                                               ;
[   37s] src/tags/ogg_tag.cc:249:17: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
[   37s]   249 |                 if (it == end())
[   37s]       |                 ^~
[   37s] src/tags/ogg_tag.cc:250:47: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
[   37s]   250 |                         return numeric_limits<float>::quiet_NaN();
[   37s]       |                                               ^~~~~
[   37s] src/tags/ogg_tag.cc:250:52: error: expected unqualified-id before ‘>’ token
[   37s]   250 |                         return numeric_limits<float>::quiet_NaN();
[   37s]       |                                                    ^
```

> With ffmpeg: probably the constness of the returned pointer has changed. Changed tho code to const AVCodec*. This seems not to harm the older versions of the API.

There are seems to be only warnings (-Wdeprecated-declarations) about src/replaygain.cc left relating to AVCodec-functions but those might become errors in next major ffmpeg version.

**Comment by maazl** [comment]
Again the same missing include. Fixed.
Probably the include was implied by some other include on my platform.

Regarding deprecated AVCodec: whatever they like. The code is mainly copied from an example on the ffmpeg site only a few weeks ago. ;-)

**Comment by v-fox** [comment]
> Again the same missing include. Fixed.
> Probably the include was implied by some other include on my platform.

Thanks, building nicely now.
It still crashes on exit but it's more of a cosmetic issue.

> Regarding deprecated AVCodec: whatever they like. The code is mainly copied from an example on the ffmpeg site only a few weeks ago. ;-)

Maybe they haven't updated those themselves. At least they are not 5-10 years behind like VLC that has its current release still tied to ffmpeg-4's age of dependencies.
